### PR TITLE
Basic docs framework

### PR DESCRIPTION
**Pull request by dcramer**
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry-elixir/57)

### CODE REVIEW

**Comment by dcramer** [comment]
This should be the bits of the skeleton needed to integrate with our docs site. Ill work on getting the related changes in place, but we can fill this in and land whenever (or even build it out of master)

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry-docs/pull/59

**Comment by jeregrine** [comment]
@dcramer I assume you just want me to fill in the blanks?

**Comment by dcramer** [comment]
That would be great. We can add or remove sections where it makes sense and can help polish it up to parity with other sdks.

**Pull request merged**
