### PR TITLE
Fix text support for Elixir 1.5 and Erlang/OTP 20.0.

### PR DESCRIPTION
**Pull request by jalcine**
> Relates to https://github.com/getsentry/sentry-elixir/issues/220.

The aim of this PR is to allow for support of Elixir 1.5.

### CODE REVIEW

**Comment by jalcine** [comment]
So initially I just bumped the version use of Erlang and Elixir to see what dependencies resulted in failures. This helped out noticing these failures:

1. Erlang/OTP 20.0 fails.
2. Elixir 1.5 just _doesn't_ work with this.

**Comment by mitchellhenke** [comment]
Can you be more specific with how the library fails or doesn't work with Erlang 20 and Elixir 1.5?

The library should be functioning on Elixir 1.5 and Erlang 20 despite surprising test failures.  The failures on Travis suggest this as well, as the failures are around a couple tests that have specifics related to Erlang/Elixir versions.

**Comment by jalcine** [comment]
Apologies for lack of clarity.

The library _does_ work for 1.5 and OTP 20; it's the act of running tests with them.

**Comment by jalcine** [comment]
This gets trickier as I go - some line numbers shift even in versions of Erlang.

Would it make sense to _drop_ line numbers as something to match against?

**Comment by mitchellhenke** [comment]
@jalcine Given the extent of it, I think dropping line numbers for core Elixir/Erlang functions is fine for the match.  I would like to at least```assert is_integer(json["stacktrace"]["frames"]["lineno"])` in it's place though

**Comment by jalcine** [comment]
That line shift was due to me adding a method - didn't notice that. No need to drop the line numbers anymore. I understand why it's done now more in depth; these values are definitive and shouldn't shift.

**Comment by mitchellhenke** [comment]
I think the `cond` works well for situations like `NaiveDateTime.from_erl/3`, as that should be way less common, but line numbers are too much of a hassle.

**Comment by jalcine** [comment]
Going to squash these commits once I get Elixir 1.3.4 + OTP < 20.0 working again.

**Comment by mitchellhenke** [comment]
Thanks @jalcine! ❤️ 💖

**Pull request merged**
