### PR TITLE
Filter Events

### LINKED ISSUE #63: Do not capture certain exceptions
Currently, sentry is capturing Elixir.Phoenix.Router.NoRouteError, which is not what we'd prefer. Is it reasonable for there to be a config key like `excluded_exceptions`?

### PR DESCRIPTION
**Pull request by mitchellhenke**
closes #63  

@jeregrine 

going to write some docs if this API works

### CODE REVIEW

**Comment by myronmarston** [comment]
👏  I'm definitely looking forward to using this!

**Comment by mitchellhenke** [comment]
@myronmarston thank you, awesome to hear 🙂

**Comment by myronmarston** [comment]
Any idea when a release might drop with this included?

**Comment by mitchellhenke** [comment]
@myronmarston I'm going to finish up #100 and #102 tomorrow, then I'll cut a release!

**Comment by mitchellhenke** [comment]
@myronmarston Just released `2.1.0`, please let me know if you see anything out of the ordinary 🙂

**Pull request merged**
