### PR TITLE
update maybe_log_send_result/2 with proper error

### PR DESCRIPTION
**Pull request by savhappy**
-When `Sentry.ClientError` was created, it was not passed updated in the `maybe_log_send_result/2` function
-This was originally found from debugging issue #788

### CODE REVIEW

**Comment by whatyouhide** [comment]
@savhappy can you refactor this so that we only have *one* `maybe_log_send_result`? I can't recall why we have two. Build the error wherever it makes sense, but then do the logging only in one place.

**Comment by savhappy** [comment]
Yes @whatyouhide the easiest is to make it public in `Sentry.Client` module. Or we can change the arrity of `Sentry.Transport.post_envelope/3` to accommodate the two uses. Which path is preferred?

**Comment by whatyouhide** [comment]
> Or we can change the arity of `Sentry.Transport.post_envelope/3` to accommodate the two uses. Which path is preferred?

Can you elaborate?

**Comment by savhappy** [comment]
Actually, I can just grab what I need from the `Sentry.Envelope` struct to pass the events to `maybe_log_send_result`. So it would look like this:


``` elixir
  def post_envelope(%Envelope{} = envelope, client, retries \\ @default_retries)
      when is_atom(client) and is_list(retries) do
    result =
      case Envelope.to_binary(envelope) do
        {:ok, body} ->
          {endpoint, headers} = get_endpoint_and_headers()

          post_envelope_with_retries(client, endpoint, headers, body, retries)

        {:error, reason} ->
          {:error, {:invalid_json, reason}}
      end

    _ = maybe_log_send_result(result, envelope.items)
  end

```

Does that seem ideal?

**Comment by savhappy** [comment]
But it breaks all of the cron tests... maybe making this function public is best? @whatyouhide

**Comment by whatyouhide** [comment]
Let's make this public and see how it looks like.

**Comment by savhappy** [comment]
Updates were made! We still need a test for `:too_many_retries` but the refactored logic should handle the bug mentioned in #792

**Review by whatyouhide — APPROVED** [review]

**Pull request merged**
