### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KamilLelonek**
Add a note about Dockerfiles.

### CODE REVIEW

**Comment by mitchellhenke** [comment]
Thanks for opening this :)

I've opened #187 in relation to #183 to investigate if we can make configuration smoother, but I don't think this documentation in its current form adds enough to be included in the README.

Trying to compile without necessary configuration files is not an issue specific to Sentry, though documentation explaining some of the complexity around source code reading and compilation could be improved.

It could be prudent to add a warning [here](https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/sources.ex#L3-L49) about the recursive file reading and a `Logger.info` call [here](https://github.com/getsentry/sentry-elixir/blob/08e14e4fb8db035980de3215d4633d88c2526359/lib/sentry/sources.ex#L53) that announces the recursive search is starting.  What do you think?

**Comment by KamilLelonek** [comment]
It's completely up to you how you will proceed with this PR and the documentation.

You now have some setup that is relevant in terms of `Dockerfile` preparation.

There are already some people who started using `sentry` again with your library after they were informed about this solution.

**Comment by mitchellhenke** [comment]
@KamilLelonek I'd be happy to link to a gist or blog post of yours that describes getting Docker and sentry-elixir set up, but maintaining docs for Docker builds within this repo is not something I am currently comfortable doing 🙂

**Comment by KamilLelonek** [comment]
OK, I'm closing it then.

**Pull request closed without merging**
