### PR TITLE
Handles String ip address

### LINKED ISSUE #115: protocol String.Chars not implemented for {:error, :einval}
As per doc, we put these inside our Phoenix router:

```
use Plug.ErrorHandler
use Sentry.Plug
```

However, this overrides Phoenix's error handler and effectively making it impossible to trace the actual error, while spitting this error:

```
protocol String.Chars not implemented for {:error, :einval}
```

Any ideas?

### PR DESCRIPTION
**Pull request by syamilmj**
Fixes #115

### CODE REVIEW

**Comment by mitchellhenke** [comment]
after some investigation, it looks like `remote_ip` should always be in the form of a tuple, based on the typespecs [here](http://erlang.org/doc/man/inet.html#type-ip_address) and [here](https://hexdocs.pm/plug/Plug.Conn.html#t:t/0).  What is the value in `remote_ip` that you're seeing that causes this to break?

**Comment by syamilmj** [comment]
On my local, it returns `"127.0.0.1"` thus causing `:inet.ntoa/1` to fail with `{error, einval}`

Elixir: 1.4.0
Phoenix: 1.2.1
Plug: 1.30

Sentry integrated in web.ex:

```
def router do
    quote do
      use Phoenix.Router
      use Plug.ErrorHandler
      use Sentry.Plug
    end
end
```

**Comment by jeregrine** [comment]
What about in your Endpoint? Also can you show us the entire Plug.Conn?
Because remote_ip 'should not' return that. The "host" can return that.

**Comment by mitchellhenke** [comment]
Do you potentially have a Plug somewhere that is modifying `remote_ip`?

**Comment by syamilmj** [comment]
Thanks for the replies. I'll investigate the issue as this seems to be unique for my setup. Closing this PR for now. Thanks!

**Pull request closed without merging**
