### PR TITLE
Additional example to handle sentry in specific environments in phoenix (README.md)

### PR DESCRIPTION
**Pull request by cdvv7788**
Following the instructions, I was receiving errors in the test environment. I added a small example of how I fixed it to the readme.

### CODE REVIEW

**Comment by mitchellhenke** [comment]
@cdvv7788 can you elaborate on the errors you are receiving?

**Comment by cdvv7788** [comment]
@mitchellhenke Just warnings when running the controller tests. Situations where normally sentry sends the message. It complains about an invalid DSN.
Obviously, setting the DSN for the test settings is not an option.
Is there a better approach to handle this?

**Comment by mitchellhenke** [comment]
Controlling the situations in which Sentry runs should be done via the `:environment_name` and `:included_environments` configuration keys. An example is [here](https://github.com/getsentry/sentry-elixir#configuration):

```elixir
config :sentry,
  dsn: "https://public_key@app.getsentry.com/1",
  # ...
  environment_name: Mix.env(),
  included_environments: [:prod]
```

**Comment by cdvv7788** [comment]
@mitchellhenke Well, my setup differs a little from what is in https://github.com/getsentry/sentry-elixir#configuration
I have the configuration in `prod.secret.exs`, to load the `dsn` from an environment variable.
If you just use the `Sentry.Plug` in the router, it will try to load sentry when it has not been configured.

I think that loading the dsn from an environment variable is a pretty common pattern. Is it still recommended to add it in the `config.exs` file, even when it is only wanted for sites that use `prod.exs` settings? (staging and prod use that one, for example).

**Comment by mitchellhenke** [comment]
@cdvv7788 The method for loading the DSN shouldn't cause any issues around this, it's an issue with Sentry's defaults, which is hard to make fit for the different use cases (though yours is a common pattern).

Sentry is trying to send events while in the `:test` MIX_ENV because the configuration for `:environment_name` is matching whatever is in `:included_environments`.

Could you try adding the following to `config/config.exs`?

```elixir
# config/config.exs

config :sentry,
  included_environments: []
```

**Comment by cdvv7788** [comment]
@mitchellhenke that worked. Does this deserve something in the readme or should I just close the PR?

**Comment by mitchellhenke** [comment]
@cdvv7788 Closing I think is fine. I've rewritten the README a little bit to hopefully make it clearer, and I'm working on some configuration-related things to make the initial setup better.

**Pull request closed without merging**
